plugins:
  resource_pool_secrets:
    executor: central_deployment_agent
    source: https://github.com/ahmadiesa-abu/resource_pool_secrets_plugin/archive/master.zip
    package_name: resource_pool_secrets_plugin
    package_version: '0.1'
